# Generated by Django 3.1.4 on 2020-12-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_service',
            field=models.TextField(blank=True, max_length=8000, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='image_service',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='about',
            name='title_service',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
