# Generated by Django 3.1.4 on 2020-12-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201216_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image_service',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
