# Generated by Django 3.1.4 on 2020-12-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201216_0645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_service', models.CharField(blank=True, max_length=200, null=True)),
                ('about_service', models.TextField(blank=True, max_length=8000, null=True)),
                ('image_service', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='about',
            name='about_service',
        ),
        migrations.RemoveField(
            model_name='about',
            name='image_service',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title_service',
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(blank=True, max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
