# Generated by Django 3.1.4 on 2020-12-16 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20201216_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image_service',
            field=models.ImageField(blank=True, null=True, upload_to='media/service'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('languages', models.TextField(max_length=800)),
                ('description', models.TextField(blank=True, max_length=8000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/service')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
