# Generated by Django 3.1.4 on 2020-12-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201216_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='image',
            new_name='about_image',
        ),
        migrations.AlterField(
            model_name='project',
            name='languages',
            field=models.CharField(max_length=800),
        ),
    ]
