# Generated by Django 3.1.4 on 2020-12-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201220_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_image',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='upload_image_path'),
        ),
    ]
