# Generated by Django 3.1.4 on 2020-12-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201220_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_image',
            field=models.ImageField(default='default.jpeg', upload_to='upload_image_path'),
        ),
    ]
