# Generated by Django 3.1.4 on 2020-12-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20201220_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_image',
            field=models.ImageField(default='default.jpg', upload_to='media/about'),
        ),
    ]
